tasks:
    install-aws-cli:
        name: Install AWS CLI
        command: |
            export AWS_CLI_AUTO_PROMPT=on-partial
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            cd $THEIA_WORKSPACE_ROOT
            echo -e "Copy and paste the following into terminal with AWS credentials: \nAWS_ACCESS_KEY_ID=[Replace with Access Key] \nexport AWS_SECRET_ACCESS_KEY=[Replace with Secret Key] \nexport AWS_REGION=us-east-1"
        triggeredBy:
            - postEnvironmentStart

##